server:
  port: 8007

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/checking # MongoDB connection URI
      auto-index-creation: true # Enable auto-index creation (fine for development/testing)
